/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author manager
 */
public class Home_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Home_GUI
     */
    public Home_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        divi = new javax.swing.JButton();
        soma = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        valor1_txt = new javax.swing.JTextField();
        valor2_txt = new javax.swing.JTextField();
        sair_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor 1 : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor 2 :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 80, 30);

        resultado_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultado_txtActionPerformed(evt);
            }
        });
        jPanel1.add(resultado_txt);
        resultado_txt.setBounds(130, 250, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESULTADO :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 240, 130, 40);

        divi.setText("/");
        divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diviActionPerformed(evt);
            }
        });
        jPanel1.add(divi);
        divi.setBounds(190, 160, 41, 23);

        soma.setText("+");
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });
        jPanel1.add(soma);
        soma.setBounds(40, 160, 41, 23);

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        jPanel1.add(menos);
        menos.setBounds(90, 160, 40, 23);

        mult.setText("*");
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });
        jPanel1.add(mult);
        mult.setBounds(140, 160, 41, 23);

        valor1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1_txtActionPerformed(evt);
            }
        });
        jPanel1.add(valor1_txt);
        valor1_txt.setBounds(100, 40, 120, 30);

        valor2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2_txtActionPerformed(evt);
            }
        });
        jPanel1.add(valor2_txt);
        valor2_txt.setBounds(100, 80, 120, 30);

        sair_btn.setBackground(new java.awt.Color(255, 0, 0));
        sair_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sair_btn.setText("X");
        sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_btnActionPerformed(evt);
            }
        });
        jPanel1.add(sair_btn);
        sair_btn.setBounds(250, 20, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 340, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 350);

        setSize(new java.awt.Dimension(305, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resultado_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultado_txtActionPerformed
        Model.Funcoes_DAO.soma();
            Model.Funcoes_DAO.menos();
                Model.Funcoes_DAO.mult();
    }//GEN-LAST:event_resultado_txtActionPerformed

    private void diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diviActionPerformed
        Model.Funcoes_DAO.div();
        
    }//GEN-LAST:event_diviActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
        Model.Funcoes_DAO.soma();
    }//GEN-LAST:event_somaActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        Model.Funcoes_DAO.menos();
    }//GEN-LAST:event_menosActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        Model.Funcoes_DAO.mult();
    }//GEN-LAST:event_multActionPerformed

    private void valor1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1_txtActionPerformed
        String valor1  = valor1_txt.getText();
    }//GEN-LAST:event_valor1_txtActionPerformed

    private void valor2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2_txtActionPerformed
        String valor2  = valor2_txt.getText();
    }//GEN-LAST:event_valor2_txtActionPerformed

    private void sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menos;
    public static javax.swing.JButton mult;
    public static javax.swing.JTextField resultado_txt;
    private javax.swing.JButton sair_btn;
    private javax.swing.JButton soma;
    public static javax.swing.JTextField valor1_txt;
    public static javax.swing.JTextField valor2_txt;
    // End of variables declaration//GEN-END:variables
}
